name: Build and Push DevContainer

on:
  push:
    branches:
      - main
    paths:
      - 'hosts/devcontainer/**'
      - 'flake.nix'
      - 'flake.lock'
  workflow_dispatch: # Allows manual trigger button

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/nix-devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker Image with Nix
        run: |
          # Build the flake output
          nix build .#devcontainer --print-build-logs
          
          # Load the result (which is a tarball) into Docker
          docker load < result
          
          # The image name is defined in your nix file (nix-devcontainer:latest)
          # We tag it for the registry
          docker tag nix-devcontainer:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # Push to GitHub Container Registry
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest