{ config, pkgs, myConstants, ... }:

let
  # The YAML configuration file for Recyclarr, automatically generated by Nix.
  # We use the internal Docker gateway (172.17.0.1) to communicate with Sonarr and Radarr.
  recyclarrYaml = pkgs.writeText "recyclarr.yml" ''
    # yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
    
    sonarr:
      series:
        base_url: http://172.17.0.1:${toString myConstants.services.sonarr.port}
        api_key: !env_var SONARR_API_KEY
        quality_definition:
          type: series
        quality_profiles:
          # Standard: WEB-1080p
          # (For the French version [French MULTi.VO] WEB-1080p, use trash_id: 4c48f506c1116a3a57ae33f12346bd15)
          - trash_id: 72dae194fc92bf828f32cde7744e51a1 
            reset_unmatched_scores:
              enabled: true

    radarr:
      movies:
        base_url: http://172.17.0.1:${toString myConstants.services.radarr.port}
        api_key: !env_var RADARR_API_KEY
        quality_definition:
          type: movie
        quality_profiles:
          # Standard: HD Bluray + WEB (1080p)
          # (For the French version [French MULTi.VO] HD Bluray + WEB, use trash_id: 2572ce3ea4eef1c19d59e0e20ed1cea7)
          - trash_id: d1d67249d3890e49bc12e275d989a7e9 
            reset_unmatched_scores:
              enabled: true
  '';

  # Location of the secure environment file where you will put your API Keys
  envFile = "${myConstants.paths.servicesSSD}/recyclarr/secrets.env";
in
{
  # Ensure the configuration directory exists and is owned by the correct user
  systemd.tmpfiles.rules = [
    "d ${myConstants.paths.servicesSSD}/recyclarr 0755 1000 1000 -"
  ];

  virtualisation.oci-containers.containers."${myConstants.services.recyclarr.containerName}" = {
    image = "ghcr.io/recyclarr/recyclarr:${myConstants.services.recyclarr.version}";

    environment = {
      TZ = "Europe/Paris";
      CRON_SCHEDULE = "@daily"; # Runs the sync automatically every day at midnight
    };

    # Inject the environment variables containing the API keys securely
    environmentFiles = [ envFile ];

    volumes = [
      "${myConstants.paths.servicesSSD}/recyclarr:/config"
      # Mount the Nix-generated YAML directly to where Recyclarr expects it
      "${recyclarrYaml}:/config/recyclarr.yml:ro"
    ];

    user = "1000:1000";
  };
}